### ISSUE TITLE
进度咨询

### ISSUE THREAD

**Issue by Lyon1994** [wtuadn/IFW#1]
这个完成的怎么样啦,我也打算写一个的,看到你这个了,有什么难点么,可以一起讨论下

**Comment by wtuadn** [comment]
> 这个完成的怎么样啦,我也打算写一个的,看到你这个了,有什么难点么,可以一起讨论下

完成了的，不过我在一加3，氢、氧os上测试都无效，可能是一加的系统不支持IFW吧，后面就没维护了，回去用写轮眼了

**Comment by wtuadn** [comment]
> 这个完成的怎么样啦,我也打算写一个的,看到你这个了,有什么难点么,可以一起讨论下

没啥难点，就是字符串操作，文件操作

**Comment by Lyon1994** [comment]
@wtuadn 好吧,那我只能接着研究吧,共勉
